# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vEy1GMOS5yjaS4E-nYNdL5m7CYO8yAsn
"""

#Convertendo os numeros (32, 57, 101 e 77) para binarios utilizando a biblioteca de terceiros a (biblioteca numpy) fica:
import numpy as np
n1 = 32
n2 = 57
n3 = 101
n4 = 77
b1 = np.binary_repr(n1)
b2 = np.binary_repr(n2)
b3 = np.binary_repr(n3)
b4 = np.binary_repr(n4)
print(f'Os numeros {n1}, {n2}, {n3}, {n4} em binario sao: {b1}, {b2}, {b3}, {b4}')